import numpy as np

def create_distance_matrix(cities):
    """
    Compute the Euclidean distance matrix for a set of cities.

    Each city is represented by its (x, y) coordinates, and this function 
    calculates the pairwise distances between every pair of cities using 
    vectorized NumPy operations for efficiency.

    Parameters
    ----------
    cities : list of tuple
        A list of coordinates, where each element is a tuple (x, y)
        representing the position of a city.

    Returns
    -------
    numpy.ndarray
        A 2D NumPy array (n x n) where each element [i, j] represents 
        the Euclidean distance between city i and city j.

    Example
    -------
    >>> cities = [(0, 0), (3, 4), (6, 0)]
    >>> create_distance_matrix(cities)
    array([[0., 5., 6.],
           [5., 0., 5.],
           [6., 5., 0.]])
    """
    
    arr = np.asarray(cities)
    diff = arr[:, None, :] - arr[None, :, :]
    dist_mat = np.sqrt((diff ** 2).sum(axis=2))
    return dist_mat

def total_distance(tour, dist_matrix):
    """
    Calculate the total distance of a given tour using the precomputed distance matrix.

    The tour is represented as a permutation of city indices. The function
    computes the sum of distances between consecutive cities in the tour,
    including the return to the starting city (making it a complete cycle).

    Parameters
    ----------
    tour : list of int
        A list of integers representing the visiting order of cities 
        (e.g., [0, 2, 1, 3]).

    dist_matrix : numpy.ndarray
        A 2D NumPy array representing the distances between cities, 
        typically generated by `create_distance_matrix`.

    Returns
    -------
    float
        The total distance of the tour (the sum of all edge distances).

    Example
    -------
    >>> dist_matrix = np.array([[0, 5, 6],
    ...                         [5, 0, 5],
    ...                         [6, 5, 0]])
    >>> total_distance([0, 1, 2], dist_matrix)
    16.0
    """
    
    total = 0.0
    n = len(tour)
    for i in range(n):
        total += dist_matrix[tour[i], tour[(i + 1) % n]]
    return total
